// frontend/vite.config.js
import { defineConfig } from 'vite';
import react            from '@vitejs/plugin-react';
import path             from 'path';

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: { '@': path.resolve(__dirname, 'src') }
  },
  server: {
    port : 5173,
    proxy: {
      // API endpoints
      '/api'        : 'http://localhost:3001',

      // raw files generated by the backend
      '/uploads'    : 'http://localhost:3001',

      // plain-text “view source” endpoint (see §2)
      '/view-source': 'http://localhost:3001'
    }
  }
});
